 # ansible n3 -m file -a "path=/home/centos/n3_dir state=directory"
---
- name: Update n3 server
  hosts: n3

  tasks:
  - name: create directory
    file:
      name: /home/centos/n3_dir
      state: directory

  - name: update content
    copy:
      dest: /home/centos/n3_file.txt
      content: hello
...